BEGIN;

DROP TRIGGER IF EXISTS trigger_update_weight_on_goal_patch1 ON goal;

DROP FUNCTION IF EXISTS update_weight_history_on_goal_patch CASCADE;
DROP FUNCTION IF EXISTS update_jsonb CASCADE;

DROP TABLE IF EXISTS note CASCADE;
DROP TABLE IF EXISTS exercise_log CASCADE;
DROP TABLE IF EXISTS exercise CASCADE;
DROP TABLE IF EXISTS food_log CASCADE;
DROP TABLE IF EXISTS food CASCADE;
DROP TABLE IF EXISTS health_indicator_history CASCADE;
DROP TABLE IF EXISTS goal CASCADE;
DROP TABLE IF EXISTS o_user CASCADE;

COMMIT;
